### ISSUE TITLE
Issue tracking for dereference branch

### ISSUE THREAD

**Issue by cedricdcc** [lifewatch/user-analysis-2023#10]
All issues mentioned in pull request for lwua-ingest but that were for the dereference branch.

- [ ] : fair signposting support if no conneg is found for ld+json or ttl representation.
- [ ] : rename METADATA_FOLDER to DEREF_TASKSTATUS_FOLDER
- [ ] : run over all functions and check if description matches functionality
- [ ] : Use pykg2tbl for returning SPARQL query results.
